### ISSUE TITLE
Not working with DrayTek Vigor2920

### ISSUE THREAD

**Issue by ghost** [j91321/rext#8]
Hello,

I have the DrayTek Vigor2920 configuration file but it can't extract the password from the backup configuration file. Here is the log:

'Traceback (most recent call last):
  File "D:\Downloads\Compressed\rext\rext.py", line 12, in <module>
    interpreter.cmdloop()
  File "C:\Program Files\Python36\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Program Files\Python36\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "D:\Downloads\Compressed\rext\interface\cmdui.py", line 100, in do_load
    loader.load_module(self.active_module_import_name)  # Module is loaded and executed
  File "D:\Downloads\Compressed\rext\core\loader.py", line 18, in load_module
    importlib.import_module(modname)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Downloads\Compressed\rext\modules\decryptors\draytek\vigor_config_old.py", line 173, in <module>
    Decryptor()
  File "D:\Downloads\Compressed\rext\modules\decryptors\draytek\vigor_config_old.py", line 43, in __init__
    core.Decryptor.RextDecryptor.__init__(self)
  File "D:\Downloads\Compressed\rext\core\Decryptor.py", line 19, in __init__
    self.cmdloop()
  File "C:\Program Files\Python36\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Program Files\Python36\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "D:\Downloads\Compressed\rext\modules\decryptors\draytek\vigor_config_old.py", line 49, in do_run
    g, outdata = self.de_cfg(data)
  File "D:\Downloads\Compressed\rext\modules\decryptors\draytek\vigor_config_old.py", line 69, in de_cfg
    return g, self.decompress_cfg(self.decrypt_cfg(data))
  File "D:\Downloads\Compressed\rext\modules\decryptors\draytek\vigor_config_old.py", line 110, in decompress_cfg
    core.compression.lzo.pydelzo.decompress(b'\xF0' + pack(">L", rawcfgsize) + data[0x100:0x100 + lzocfgsize])
  File "D:\Downloads\Compressed\rext\core\compression\lzo.py", line 90, in decompress
    dst, dst_off, dst_len)
  File "D:\Downloads\Compressed\rext\core\compression\lzo.py", line 124, in int_decompress
    while src[ip] == 0:
IndexError: bytearray index out of range'

I have check that the def de_cfg(self, data) method does not work. I have print the array after processing and it all the \x00.

**Comment by ghost** [comment]
Here is the sample file: https://drive.google.com/open?id=1gpH2o8HJ5sA9y9c6jdVlm6oZ3J4ifQ_-

**Comment by GunterO** [comment]
I'm encountering the same problem. Did you found a solution? Thanks!

**Comment by j91321** [comment]
Unfortunately not, the compression for Vigor2920 may be different, but I don't remember exactly what was the problem.
